/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_18 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn,
    output reg [15:0] boolean
  );
  
  
  
  always @* begin
    boolean = a;
    
    case (alufn)
      4'h8: begin
        boolean = a & b;
      end
      4'he: begin
        boolean = a | b;
      end
      4'h6: begin
        boolean = a ^ b;
      end
      4'ha: begin
        boolean = 1'h1;
      end
    endcase
  end
endmodule
